### ISSUE TITLE
Add notice about usage of shipped opengl32 lib

### ISSUE THREAD

**Issue by RattleSN4K3** [UltraStar-Deluxe/USDX#115]
opengl32_.dll is pushed to the installer and already included in the portable installer without mentioning the use of it. Add a description why it is useful and how it can be used.

**Comment by RattleSN4K3** [comment]
Can you actually explain why the file is required? And also why this issue is closed...

Even if is is explained in IRC, on the MLK page or anywhere else, it should be notified in a file, or atleast it should have been stated once the file got added.

4dc39f17329e314e4ee10f1ec8442a1e36fbacb7

Judging by the 2 commits 61cc4a4f987bec3ca5c433ce84125da888c1b2e7 and 18f4bd0d6189cec52ed1b8716c06c098ab69696f, the problem exists on one of your systems. Please, elaborate.

Opening the issue again...

**Comment by basisbit** [comment]
as you can read in the spanish and the german community forums, many systems especially now with the release of windows 8.1 and windows 10 don't come with graphics cards drivers which provide accelerated and compliant OpenGL stuff. Stuff like this is normal for Microsoft as they want people to use their proprietary DirectX solution.
Especially hardware based on intel core 2nd gen or older CPUs or graphics cards from ati/nvideo from the same timeframe didn't get any new drivers from the manufacturers either. Graphics card drivers for windows 7/8.0 don't work on the newer windows versions any more because of changes in the wddm.
Sometimes the leshcat drivers will work but these tend to be quite buggy on many systems.
Thus software based opengl rendering is the last possibility to get usdx to work on those systems.
The windows opengl renderer is a 10 years old horrible piece of single threaded software. The opengl32_.dll whcih originates from the mingw/cygwin project is a good, fast and efficient alternative which makes USDX quite well playable on many of the affected systems.

**Comment by RattleSN4K3** [comment]
That's what I know. But all these things are **not documented** for this release. It was mentioned in forums you mentioned but not in a release log, a readme or documentation (or simple related file).

The docs simply state:
> 11.1.3 Error message “Failed Loading Open GL 1.2 ...”
Update the graphics drivers. See section 11.1

It would/could help if such workaround is documented there or anywhere in order to help people having problems with it (without the need to check forums).
