### ISSUE TITLE
[Feature Request] Allow to jump over long sequences without lyrics using S

### ISSUE THREAD

**Issue by bohning** [UltraStar-Deluxe/USDX#173]
This is already possible at the beginning of the song, but it would also be useful for songs with long instrumental parts. Pressing S could jump to 5 seconds before the next lyrics (enabled if instrumental parts exceeds a certain threshold, for example).

**Comment by basisbit** [comment]
we discussed this at a physical meetup in detail already and decided to not implement jumping within the song in the default UltraStar Deluxe master branch. Most music is considered to be art and the artist usually intends the song to have these long breaks for a reason. We want people to enjoy the good music, which includes these long instrumental parts. Additionally, these keyboard interactions would disturb from the game playing experience.
If a song is not suitable for karaoke because of too long "breaks" inbetween, the creator should just cut the audio+video file accordingly.

**Comment by basisbit** [comment]
If you don't agree with the reasoning, please tell us so.
This is an open & free project, thus it is important that others tell us if they disagree and why they disagree.

**Comment by bohning** [comment]
On the one hand, I agree. On the other hand, then this argument would even go against the functionality of skipping long intros at the beginning using S. I have found this new feature quite handy, less during actual game play, but more while checking songs. So it's a feature that would be nice to have, but which I would not consider crucial. A 5 minute instrumental solo may disturb the game playing experience more than I quick key press, I guess. So it would be up to the user to use the functionality or not. But again, it's nothing I desperately need.

In fact, today I was testing to see if it works while fixing songs that needed #END tags. The editor cannot be used for this, because it limits access to where there are lyrics. So in order to check if the songs ends as expected with the #END tag, you have to let it play and keep an eye on it...

**Comment by basisbit** [comment]
also, this is a duplicate of #90

**Comment by bohning** [comment]
True, I missed #90, sorry for that.
