### ISSUE TITLE
String encoding issue with input name

### ISSUE THREAD

**Issue by gunchleoc** [UltraStar-Deluxe/USDX#179]
I have a German-language Windows 7 with system locale set o Scottish Gaelic (GB). The sound card inputs etc. are therefore displayed in German - which is fine, anything else would be a coding nightmare.

However, the "ä" in "Hauptlauststärke" (= Main volume) isn't shown with the correct encoding:

![encoding_issue](https://cloud.githubusercontent.com/assets/4095570/20836302/a65e5528-b896-11e6-888d-75f534c9c8a5.png)

**Comment by RattleSN4K3** [comment]
It's unrelated to the selected language. IIRC the name is returned by the system and isn't converted.

**Comment by basisbit** [comment]
@RattleSN4K3 yes, but the ANSI encoded string is not correctly passed from SDL2 to our freepascal code and thus, the ä is not shown correctly. This issue is not so easy to solve, because the SDL2 code is supposed to pass an UTF8 string according to its specification, but instead just forwards the data from the system. In the #SDL chatroom at freenode, the developers were not sure how to handle this - either fix it by reencoding to UTF8 and thus maybe breaking existing implementations or just keep it how it is and adjust the api specification

**Comment by basisbit** [comment]
took another look on the code, and we were not affected by the sdl issue, because we use bass or portaudio for audio input. gonna fix this now.

**Comment by basisbit** [comment]
this was fixed by f0f48616aa6d77881e0393801c5194ab63b02f31
