### ISSUE TITLE
First-run record settings popup

### ISSUE THREAD

**Issue by sleumas2000** [UltraStar-Deluxe/USDX#22]
Whenever the game is launched and there are no record settings, it might be prudent to alert the user as soon as they run the game that they need to set their record settings, and maybe to set them to defaults (would require OS-specific code), and inform the user of the setting

**Comment by basisbit** [comment]
this is now implemented with commit f4ff219 . It a) validates the record settings and b) checks if a working microphone is configured for player 1. Checking for the other possible players at game startup would not make sense because it isn't clear at that point in time how many players want to play. Anyways, the implemented solution covers all useful cases.
