### ISSUE TITLE
threads leaking after #269

### ISSUE THREAD

**Issue by basisbit** [UltraStar-Deluxe/USDX#282]
Builds on Windows don't properly shut down them self anymore when the user tries to properly exit the game. The game seems to be leaking some threads which are not exited by `halt;`. Was not able to get any useful information by debugging and was not able to receive any help on freenode#fpc on how to debug leftover threads issues.
By testing various builds, I think this problem is related to the changes in #269. Maybe these problems existed already before but didn't show up?
Any help would be very welcome!

**Comment by s09bQ5** [comment]
As I said in #269, leaking threads does not cause the problem. Leaking threads before #269 hid the problem.

Lazarus appears to be using gdb for debugging even on Windows. Do you have any way to execute "thread apply all bt" on a build with debug symbols/line number information?

**Comment by basisbit** [comment]
so, after wasting bunch of weeks trying to fix this issue, I give up. Was not able to get usdx to actually close on windows. Thus can't do a release. And without a release, usdx is currently not usable on most computers out there because of the search feature not working.

**Comment by s09bQ5** [comment]
To wrap this up, the call to FreeConsole introduced by d2b3b2e0a78b0e8d93d183bf09d71e58ea58dfcc caused the EventHandleThread in unit WinEvent to no longer work correctly, so that the application was stuck forever waiting for the thread to terminate when the event handlers were unregistered on exit. It is assumed that all of this would not have happend if the OpenCV unit did not pull in the Dialogs unit, which in turn pulls in the Drivers unit, which calls InitSystemMsg on startup. The issue was fixed by removing the call to FreeConsole in e059c121e76a09c5f606a89d1be81a9fdd07daeb.

**Comment by basisbit** [comment]
the problem is not fixed, because now one can only play usdx on windows when this console is active. Anyways, this workaround is good enough for now, and will not exist any more when the usdx rewrite is done.
