### ISSUE TITLE
using the reset hotkey resets the song/video but doesn't reset the position of the lyrics

### ISSUE THREAD

**Issue by vesper8** [UltraStar-Deluxe/USDX#376]
So I was playing around with the hotkeys to see what's available. I'm using the very latest version by the way which I built using the master today on OSX

The key R starts the song/video from the start. And the key S moves the cursor to the beginning of the lyrics, for those songs that have a lot of instrumental before the song starts

Using S off the bat works well. But I noticed that using R to start the song over doesn't reset the lyrics.. if you're 2 minutes in and are seeing the lyrics from 2 minutes in, then pressing R will start the song over but the lyrics are still 2 minutes in

I think this is a bug

And here is a feature request, additionally.. it would be cool if it was possible to move through the song using the left/right arrows for example. Additionally it would be cool if it was possible to offset the audio using the [ and ] keys for example.. for those cases where the video is out of sync with the lyrics by 1 second or sometimes 100s of milliseconds

Cheers! Thanks for working on this!

**Comment by basisbit** [comment]
Hi @vesper8, thank you for your feedback!
Regarding what shortcut/keys can be used, there is a list in the [README.md](https://github.com/UltraStar-Deluxe/USDX#4-controls) in the main folder of this repository. It also contains information about what keys can be used to offset audio/video and so on (which only works when audio and video are separate files).

Regarding your bug report: this is not a bug, but instead as designed. Otherwise this would render the points tracking kind of useless, people could cheat by just re-singing parts of the song once they made a mistake. There was already quite some discussion about what to allow the players to do, when we implemented this feature. Of course any developer may feel free to change that behaviour, do a pull request and thus suggest improvements!

Regarding your feature request: I am sorry, but we have to deny your feature request because that would a) completely break multiplayer gaming experience, b) make any highscore counting useless and c) this would eventually cause feature creep. Maybe some tutorial / training game play mode would be a good addition instead.

As a general suggestion regarding how to submit issues at github: Please create one issue for exactly one topic - please don't mix bug reports and feature requests like above. Also, it is considered rather rude to not use the issue text template - the goal of such a template is to reduce the amount of work for project maintainers who usually do all this in their free time. So, please be so kind and stick to the issue template next time you open a new issue in any project which uses issue templates. Thanks!
