### ISSUE TITLE
contribute

### ISSUE THREAD

**Issue by miathedev** [UltraStar-Deluxe/USDX#423]
Strange question yes - but,

what software process model are you using and where can I see what needs to be made? I would like to participate in the USDX development. Im using USDX for at least 4 years now - i thought its time to contribute something.

Actually my skills are:

jenkins - in general ci - im managing huge build/ deployment server and their workflow currently.
java - spring - all about microservices - java8
C - a long time ago i used to write software in C for those old avr mcus....

The languages i speak
english - not as good as my german
german
a bit of spanish

does the project have a "nightly builds" server already? As example, i could host and manage that.
Im really sorry for my english - please ask, if you got problems reading my sentences.

I would feel glad to be able to contribute sth back.
Greetings, mia

**Comment by miathedev** [comment]
Vielen Dank für deine Nachricht @s09bQ5 
Ich schau dann zwischendurch in die Issues.
(Object) Pascal hätte ich ehrlich gesagt nicht erwartet.

Gibt es vielleicht sogar ein Tochter Projekt USDX neu zu entwickeln? "huge chunk of legacy code" klingt nicht sehr nach freude.

Wie gesagt, ich schau mal in die Issues rein und versuche einen Teil beizutragen.

**Comment by tiststorm** [comment]
@miathedev Ich weiß nicht in welchem Verhältnis UltraStar Deluxe und UltraStar Play zu einander stehen, aber soweit ich es verstanden hab ist das ein Rewrite, welches sich noch in den Startlöchern befindet: Das ganze arbeitet mit Unity, in C# fühlst du dich mit Java-Hintergrund wahrscheinlich wohler.

**Comment by basisbit** [comment]
Hello @miathedev !
USDX is a typical community driven free libre open source software project where any developer can contribute kind of like the "Bazaar" model from https://en.wikipedia.org/wiki/The_Cathedral_and_the_Bazaar .
In accordance to the code license, everyone can create code changes, use the github pull request mechanism to suggest changes and then discuss with other developers. Once a developer is a common main contributor, they may directly commit smaller changes to the master branch, but are advised to still use pull requests for bigger changes or when proper discussions or testing is needed.

Thank you a lot for offering to set up a build server on your private infrastructure, but it is best practice for such projects to rather use "publicly available" infrastructure or "free for public" services (travis-ci, github, appveyor,..) where possible, so the project is more independent from single people and survives for many years even if most or all developers leave the project at some point in time.

Regarding the project [UltraStar Play](https://github.com/UltraStar-Deluxe/Play) which @tiststorm mentioned: that is a separat project with a similar goal as UltraStar DX, but uses C# as development language, Unity as framework and uses a more permissive license (thus code from USDX can't be copied, except if the dev who originally wrote it does the copying). US Play was mostly started because of USDX is written in objective pascal (limiting the development tools) and tons of its code is kind of legacy code which makes it hard to maintain the project or even port it to new platforms.
Personally, my hope is that eventually US Play catches up to the amount of feature that are already available in USDX, and then whatever software is better, will survive in the long term. Initially, US Play will probably only cover the basic use cases like singleplayer sing-along-karaoke so people can also use usdx .txt files to play karaoke on smartphones, tablets, smart TVs, game consoles and similar, while USDX will still be the main program for PC (Windows/Linux) karaoke playing for a long time.

**Comment by brianch** [comment]
Just to make a small correction, I for one do prefer object pascal, and I'm pretty sure at least mischi does too (one of the old devs, currently inactive).

In my humble opinion the difficulty in maintenance is much more due to the code being super old than anything related to the choice of language.

And sorry for being a bit off topic, but talking about maintenance I think I will try to remove the unused variables and maybe look into other compiler warnings, sometimes I feel the code will shrink to half the size only by removing this unused stuff :smile:

**Comment by kamischi** [comment]
I see my name, I see Pascal → I upvote ;-)

**Comment by basisbit** [comment]
yes, sorry, that comment from me regarding the language of choice is only a religion thing... should not have mentioned it. Will try to remember that for next time 😛

**Comment by kamischi** [comment]
don't worry. alles gut.
