### ISSUE TITLE
Windows Defender reports installer to contain a trojan

### ISSUE THREAD

**Issue by andiwinter** [UltraStar-Deluxe/USDX#479]
When downloading the installer (UltraStar.Deluxe_v2017.8.0.stable_installer.exe) Windows Defender reports the following serious thread (the app contains the following trojan, allowing the execution of remote commands):
Trojan:Win32/Occamy.C

Windows 10, Version 1903 (Build 18362.295)

**Comment by basisbit** [comment]
this issue is a duplicate of #368. The usdx installer uses the same version of the nsis installer as some malware uses. Microsoft uses tools to automatically generate detection patterns to detect certain malware - sadly, these pattern generators are shitty and don'T know that what their pattern actually checks for is just some older version of the often used nsis installer.

**Comment by basisbit** [comment]
Also, there is an information at the usdx.eu website in the download section about this. Apparently many people don't read that but instead just click the download button.
