### ISSUE TITLE
Grouping songs

### ISSUE THREAD

**Issue by mq1qm** [UltraStar-Deluxe/USDX#484]
Hello there,
Is it possible to group songs of an artist to make browsing my Ultrastar database easier? I've got at least 2000 tracks, so it's a bit difficult to swipe all of them.

Thanks in advance!

**Comment by pb-programmer** [comment]
Yes that's possible but it depends on what version of UltraStar Deluxe you are using.

#### For the latest release version (2017.08.0-stable):
On the main screen go to 'Tools', then select 'Options'. In the options screen select 'Game' and set 'Tabs' to 'On' and 'Sorting' to 'Artist2'. 

#### For the latest master-branch code (self compiled):
Same steps as above, but 'Sorting' has to be set to 'Artist'. 


Very important: **With either version you need to restart the game after changing the settings!**
Otherwise the changes will not apply correctly and navigation will be buggy and/or the changes will not be displayed at all.

You can change the grouping by playing around with the 'Sorting' option (e.g.: group by first letter of artist name, group by year, group by directory for manual groups, ...) and maybe changing the 'Song Menu' to 'List' might improve the experience.

Just as general FYI: You can search for specific songs or a single artist by pressing 'J', 'page up/down' will jump to the next letter of the 'Sorting' category (so e.g. if you sort by artist and *Selena Gomez* is currently selected 'page down' will bring you to the first artist in you library that starts with 'T') and with the UltraStar-Manager (found here on github as a different repository of the 'UltraStar Deluxe' project) you can very conveniently create printer friendly lists or html-only websites with all songs in your library. That way people see all the songs without scrolling through the whole library in UltraStar itself.
