### ISSUE TITLE
Usual latency problems with a solution for next versions?

### ISSUE THREAD

**Issue by alexaf2000** [UltraStar-Deluxe/USDX#506]
### Actual behaviour

Big latency in all system operatives.

### Expected behaviour

Fast response between the microphones and the speakers

### Steps to reproduce

Tried with Linux versions and Windows.

### Details

Is usual to find the latency problem with UltraStar, but I think that if we try to improve this problem between all the systems operatives can be solved.

In Linux by using the command "pactl load-module module-loopback latency_msec=1" you can listen the microphone without any latency, so I think that is usable with the game start on a newer version of UltraStar, and in Windows exists solutions as ASIO4ALL, that allows you to listen the program that uses ASIO and your microphone with low latency. Why not implement this two solutions?

**Comment by s09bQ5** [comment]
Latency can be compensated for in the Tools >> Options >> Game screen.
The only drawback is that with a high latency singers can no longer take the recorded pitch being drawn onto the notes as an indication for the current position. They must look at the coloring of the lyrics.

> Why not implement this two solutions?

Because we are currently using PortAudio and BASS.

What is module-loopback doing internally to achieve that low latency? Can we do the same without switching from PortAudio to PulseAudio? Is it just using a small number of very small fragments?

From a maintenance standpoint it would be beneficial for us to switch to the SDL API both for playback and recording (needs SDL >= 2.0.5). The library has an active community, it is cross platform, and we already use it for several other things.

For portable low latency audio I'd use JACK, but setting up the JACK server is not as straightforward as I would like. PortAudio and SDL can use JACK as audio backend. There are also JACK source and sink modules for PulseAudio.

**Comment by alexaf2000** [comment]
But this problem also exsits on Windows. I think that the PortAudio and BASS is a legacy option... Maybe would be easier in C++ than in Pascal the use of those others options.

**Comment by basisbit** [comment]
The microphone input and game audio output latency of UltraStar Deluxe is already very good. 
ASIO does not work for all devices (installing custom drivers is not an option).

If your problem is that there is too much latency for audio input feedback from microphones directly to speakers: that feature in usdx is experimental and does not get any support. Instead, use device driver settings / hardware solutions for that.

**Comment by s09bQ5** [comment]
Btw., JACK on Windows relies on PortAudio, so it can't be that bad.
https://github.com/jackaudio/jack2/blob/608cfbe74cceaedea58c746f19117e568c5f8728/windows/README#L42
