### ISSUE TITLE
Compile USDX for Web assembly

### ISSUE THREAD

**Issue by marktkram** [UltraStar-Deluxe/USDX#558]
Is it possible to compile USDX for web assembly so it can be run in a browser ?

There is a fpc web assembly compiler in the [wiki](https://wiki.freepascal.org/WebAssembly/Compiler). 
But i get an missing objpas unit error.

An alternative may be to compile with fpc to llvm and then use [emscripten](https://emscripten.org/index.html) to create the web assembly file.

Do you see a possible way to do this ?
Other ideas are also welcome :)

**Comment by basisbit** [comment]
Web assembly target is not supported currently. There are various third party dependencies that will make it difficult for you to make usdx work on webassembly, especially the legacy OpenGL 1.x drawing stuff, audio access, hardware accelerated ffmpeg, and various other libraries that usdx uses. I'll close this issue for now because web assembly is not supported by us. If someone starts work on the task and get some progress done, it can be reopened so that developers can work together and document their progress.
