### ISSUE TITLE
Bad Z-indexing of UI (reflection effects covers menus)

### ISSUE THREAD

**Issue by Avispa** [UltraStar-Deluxe/USDX#604]
### Actual behaviour
Z-indexing of the reflection effect of UI items appear to be wrong. They sometimes overlap with imformative items/UI. So the reflection of a blue surrounding box of song/titles covers the menu line with the key-hints for example. (Depending on the selected song selection display mode.) But also generally you can see artifacts in other UI items dude to wrong Z-index.

![image](https://user-images.githubusercontent.com/25295052/158231527-345ee94d-7f25-442b-81c4-af57ab2fb840.png)

### Expected behaviour
There should be a distingtion between *real* items/UI and just FX. The later should never overlap with the former. 

### Steps to reproduce
1. Open the ultrastardx.exe
2. Set song selection to something with blue big boxes (Dont recal specifics but something like `carousel` or `slide` I guess.
3. Observe other UI items close to it getting overlaped and covered with the reflection effect of other items above it (y-achses).

### System
- USDX version: **2020.4.0 stable**
- Operating System: **Windows 10**

**Comment by barbeque-squared** [comment]
This is probably caused by something inside the gigantic `TScreenSong.Draw` function: https://github.com/UltraStar-Deluxe/USDX/blob/d448183cdc07ef8f605e6a2d01390805368e8950/src/screens/UScreenSong.pas#L3216

I'll see if there's a quick fix that would make it workable for the time being (it's possible that fixing this breaks something else, in which case I'm not willing to put more effort into it because that entire file is quite a pain to work with).

**Comment by barbeque-squared** [comment]
this was actually also happening on other screens (see the PR) and changing it in the central case appears to have fixed it everywhere
