### ISSUE TITLE
Respect #START value to shorten time line, so that the time line always starts at the beginning

### ISSUE THREAD

**Issue by bohning** [UltraStar-Deluxe/USDX#610]
**Please, do not create duplicate issues**

### Actual behaviour

If a song uses a #START tag to skip an intro (given in seconds), the time line still shows the song from the beginning of the file, so with the #START, it kinda starts in the middle of nowhere. For the #END tag to skip an outro (given in milliseconds, unfortunately it is not consistent), the skipped part is not shown in the time line (as if the song really ended at #END).

### Expected behaviour

The time line should respect both #START and #END in the same way, effectively shortening the time by both #START and #END.

### Steps to reproduce

Set #START (in seconds) and #END (in milliseconds) and look at the time line in the sing screen.

### Details

Provide some additional information:

- USDX version: latest (has probably always been that way)
- Operating System + version: macOS (is the same on all OS)

**Comment by Avispa** [comment]
Quickly checked on Windows 10 for the #START flag/tag and it's fine here with the timeline (assuming we are talking about the long line on the bottom that represents the whole song.)

Therefore I have some odd behaviour of the blue syllables indicator maybe.[1] It runs on the first line which is empty for whatever reason and on (the theoretical) contact with the first syllable (on the empty line) the actually lyric jumps from the wrong second line to the first/current line and everything is fine from here on.

__
_[1] I say maybe because I just checked on "this" one song and the lyric file is a bit weird in the first two lines in comparison to 3-4 other lyric samples I quickly compared it to. Lines are:
```
F 0 0 0
- 2
```

**Comment by barbeque-squared** [comment]
Yeah this is about the long lime on the bottom.

Can also confirm this on compiled-from-git Linux versions, has happened since at least 2021 but probably earlier too. I have a bunch of hour-long tracks that also have separate 'chapters' (with each chapter being its own txt), and these don't have a zero-length note anywhere, so I don't think your 'maybe' is causing this. Mine look like this:
```
#START:1735
#END:2014800
: 47149 7 9 Look
```

I'll see if I can find whatever bit of code is causing this later today/this week, wouldn't be the first time there's a Windows-only statement around a perfectly generic bit of code.

**Comment by barbeque-squared** [comment]
Okay, I think there's actually multiple things going on here:

### The 'boxes' inside the time bar
They're drawn by `UScreenSingView.pas` in the method `DrawInfoLyricBar`. I did some log-dumping of variables, and though I don't understand all of them, the `ww` variable appears to be some kind of "the length of the song, in beats" kind of thing. There's also the `SongStart` and `SongEnd` variables.

One thing that's wrong for sure is the `if ... then Continue;` line, but I haven't yet figured out what all of the variables do exactly. If I change it to this:
```
if (Tracks[CurrentTrack].Lines[LineIndex].Notes = nil) then Continue;
      pos := (Tracks[CurrentTrack].Lines[LineIndex].Notes[0].StartBeat - SongStart) / ww*w;
```
it at least draws boxes, except that now it's the first _sentence_ that marks the beginning of the time bar, not the actual song start. I think it's the `SongStart` variable that needs correcting here (in combination with the above changed two lines)? It should do.... something with `CurrentSong.Start` I suspect, but don't ask me what.

### The progress indicator itself
This gets drawn in `UDraw.pas` in the method `SingDrawTimeBar`. It appears that `LyricsState.TotalTime` does already take the END tag into account (but not START?). The bar itself just goes from 0.0 to 1.0, I'm not sure if it can get at the required variables currently.

I'm also not sure why this isn't all inside `DrawInfoLyricBar` anyway, since that also gets called every redraw and thus basically draws useless boxes ~50% of the time. Because unless the one there doesn't get updated, that _does_ have access to `LyricsState` as well.

**Comment by barbeque-squared** [comment]
[usdx610.patch.txt](https://github.com/UltraStar-Deluxe/USDX/files/9747918/usdx610.patch.txt)
Mostly there, but I'm pretty sure there's a way to do this without the `xWithGap` and `GAPxStart` variables. Also not the biggest fan of re-using the `br` variable, but I don't really know what it stands for in the first place.

There's an edge case where if you start doing Ctrl^Left on songs that have a _huge_ `#START` value, then the progress indicator starts going the wrong way towards the left. Similar things will probably also happen if a song goes 'past' the supposed end. Sure, you can just clamp it, but there are other issues for these (minor visual) bugs anyway.

Feel free to take this as a starting point and create a proper PR with it. Otherwise I'll probably create one as-is over the weekend. If so, I will check that it doesn't break duets, but I never use Medleys nor any kind of 'Party' mode.
