### ISSUE TITLE
Error Reported

### ISSUE THREAD

**Issue by Leilakie21** [UltraStar-Deluxe/USDX#626]
**Please, do not create duplicate issues**
Error appears when selecting Sing, Game does not play. Message displayed in image provided.

### Actual behaviour

Tell us what happens

![Capture](https://user-images.githubusercontent.com/118857270/203429277-9225694f-c762-4cae-b09d-77157cf279a6.JPG)

### Expected behaviour

Tell us what should actually happen

### Steps to reproduce

Please supply step-by-step instructions so that anyone with the same environment can reproduce the issue. Whenever you offer a description, imagine
yourself in the shoes of someone who has never encountered this problem before and would like to know exactly how to observe it under a given set of conditions.
Here is an example:

1. Open the ultrastardx.exe
2. Click on button X, then on the menu that appears, click Y
3. Wait for 3 seconds, and note the appearance of an unexpected message

### Details

Provide some additional information:

- USDX version:
- Operating System + version:

**Comment by s09bQ5** [comment]
Can you think of any reason why it is unable to create config.ini in C:\Program Files (x86)\UltraStar Deluxe\? Is this directory maybe owned by Administrator while you are running the game as normal user? Or is the directory marked as read-only?

**Comment by Leilakie21** [comment]
It should be as normal user, and this is happening on both the 2017 and
2020 versions, the same message keeps popping up

**Comment by barbeque-squared** [comment]
Can you check how the Properties -> Security tab looks for you, specifically the one for Users ?
![2022-11-23-windows-usdx](https://user-images.githubusercontent.com/5775429/203549567-8a382e53-a323-492a-96aa-f3c592d8ff8e.png)
I don't know why the checkmarks for Modify and Write are black in that screenshot (I never modified any of my settings there, I think) but those might be important if you're running as a normal user. I can't really test if this is actually the thing that does it since my own account is an Administrator, but even with that I've had something similar happen to me in the past, where some game couldn't download its updates anymore because Windows Update had messed with the permissions.

If you're sharing the computer with other people, there's probably a way to do it for only one (or some) specific users instead of all users.

**Comment by Leilakie21** [comment]
Thanks so much, I will check that out and let you know how it goes.

Sincerely
Leila Abrahams

**Comment by Leilakie21** [comment]
Hello
That solution worked, thank you so much for your help.

Sincerely
Leila Abrahams
