### ISSUE TITLE
Update compilation instructions

### ISSUE THREAD

**Issue by nmxcgeo** [UltraStar-Deluxe/USDX#635]
### Actual behaviour
The Ubuntu compilation instructions for Ubuntu in the [Readme.md](https://github.com/UltraStar-Deluxe/USDX#compiling-on-linuxbsd-using-make) and in the [wiki](https://github.com/UltraStar-Deluxe/USDX/wiki/Compiling-UltraStar-Deluxe) differ and partially don't work. 

### Expected behaviour
The compilation instructions provide a way to successfully compile Ultrastar Deluxe. They are consistent (e.g. by only having them in one place). 

### Steps to reproduce
1. Find the compilation instructions in the wiki
2. Install needed packages on Ubuntu 22.04
3. Get errors
```E: Unable to locate package ttf-dejavu
E: Package 'ttf-freefont' has no installation candidate
```
4. Step 4 of the wiki instructions don't work, because `./autogen.sh` mentioned in the Readme.md is missing. 

The needed package from Ubuntu 22.04 onwards seems to be named `fonts-dejavu` and the `ttf-freefont` package seems to be redundant. 

Greetings Nmxcgeo

**Comment by HermannDppes** [comment]
Since I was confused, for the potential benefit of future readers: The file `./autogen.sh` is present but the wiki is missing the instruction to execute it. Consequently, the further instructions fail.

In the (otherwise unrelated) issue #503 @basisbit indicated that they'd rather move documentation in general to the wiki. If that is still the case, it seems to me that it would also make sense to have the compilation instructions there and get rid of them in the README (just having a link to the wiki, I guess) so that future inconsistencies are avoided. But this has the disadvantage that the process of contributing to the wiki is not documented and capital-PR Pull Requests don't work. [1]

[1]: You may however pull from https://github.com/HermannDppes/USDX.wiki.git where the compilation instructions match the README and I made some other changes years ago without remembering their rationale by now … which is not exactly optimal.

**Comment by barbeque-squared** [comment]
@HermannDppes doesn't that issue have a different target audience though? That's more for end users, whereas compilation instructions is much more a developer thing. As such, personally I'd rather keep it in the repo (perhaps in a separate `COMPILING.md` if it gets too big) and put stuff like the keyboard controls in the wiki (and link to that).

As for the actual issue here, I used the [Arch package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ultrastardx-git) as a starting point on my system, but I need to see what modifications I made. Especially things like the `--without-portaudio` flags don't appear to be documented much anywhere either.

The freefont vs dejavu thing feels logical (I think a similar thing happened in Arch at some point), so that should at least be pretty easy to fix in the README. Not sure what to do about the wiki though, though if there's no other differences, could just turn it into a placeholder page that only links to here for the time being?

**Comment by nmxcgeo** [comment]
> Not sure what to do about the wiki though, though if there's no other differences, could just turn it into a placeholder page that only links to here for the time being?

I don't really mind, where it is documented. To me it feels more important to have it consistent and avoid redundancies. Therefore removing the wiki content and putting a link to the README seems fine.

**Comment by barbeque-squared** [comment]
The README should now be better, but I'll keep this ticket open until the wiki has also been updated. I'll create a wiki PR for that hopefully within a week.

**Comment by barbeque-squared** [comment]
I've made some updates to the wiki and opened #653 to make the README a bit smaller while I was at it.
(the YOLO way we have to edit the wiki is very much suboptimal, I wonder if we can't just have the wiki contents as a folder in the main repo and then sync it somehow)

**Comment by HermannDppes** [comment]
> the YOLO way we have to edit the wiki is very much suboptimal, I wonder if we can't just have the wiki contents as a folder in the main repo and then sync it somehow

This is [absolutely possible](https://stackoverflow.com/a/58692638) and the syncing can also be [automated with GitHub-actions](https://github.com/devonfw/devon4j/blob/develop/.github/workflows/github_actions.yml), it seems.

**Comment by barbeque-squared** [comment]
The branch is now merged into master, and for the wiki I've created follow-up item #660

**Comment by nmxcgeo** [comment]
Thanks for the updates. The instructions in the README.md work for me now.
