### ISSUE TITLE
AppVeyor CI is very slow

### ISSUE THREAD

**Issue by barbeque-squared** [UltraStar-Deluxe/USDX#661]
### Actual behaviour

Some/multiple CI jobs are very slow. Too slow. Example: https://ci.appveyor.com/project/basisbit/usdx/builds/46404802
| job | duration |
| :--- | :--- |
| Image: Visual Studio 2015; Configuration: x86-32 | Succeeded in 2 min 23 sec |
| Image: Ubuntu; Configuration: x86-64 | Succeeded in 24 min 8 sec |
| Image: Ubuntu; Configuration: x86-32 | Succeeded in 37 min 40 sec |
| Image: Ubuntu2004; Configuration: x86-64 | Succeeded in 26 min 41 sec |

Most of the time appears to be spent... compiling custom versions of FFmpeg and SDL and the like. Can't we just install some package? Or use images that have it pre-installed?

### Expected behaviour
Ideally the entire CI (all jobs together) can be run in under 15, maybe 20 minutes. Ideally we'd also have concurrency or reusing artifacts from other jobs if that's possible/relevant, but maybe we can start out be just getting every job under ~5 minutes and then go from there.

There are other issues with the CI but this is probably the biggest one right now.

**Comment by s09bQ5** [comment]
By design AppImages are supposed to be compiled on the oldest Linux distribution that works. And everything inside the AppImage should be as new as possible. So we have to build the dependencies ourselves. Usually the dependencies are cached, but sometimes the cache gets invalidated when dl.sh or tasks.sh is changes.

Building a Flatpak involves building every dependency that is not available in the runtime environment. It would be possible to cache this, but AppVeyor limits the cache to 1GB per account. I wrote about this a while back in #565. Once we have a new release, I will register USDX on flathub.org, so that we no longer need to build the Flatpak on AppVeyor. But this also means that we won't have Flatpaks for PRs, only for releases.

Maybe we should resurrect the Travis builds? There was no official cache limit IIRC. But Travis didn't store build artifacts and the upload to transfer.sh at the end of the build.sh script was a common cause for build failures.

**Comment by barbeque-squared** [comment]
Heh, it shows that I don't know that much about AppImage and Flatpaks. I have no experience with Travis, and AppVeyor does work, it's just annoying in a situation like yesterday. It's worse when I'm creating a bunch of small PR's, because every PR takes about 1.5 hours.

Some other solutions could be for example:
- make the `branch` appveyor job only run on master. If people need it while developing something, just create a draft PR so that the `pr` job picks it up. Right now it creates duplicate jobs if you create a branch in this repo and PR it.
- disable flatpak builds for PR's unless something changes in certain files/directories.

Not sure if/how easy any of those are to implement. Master builds would still be slow, but admittedly, yesterday's situation was fairly unique. Faster PR's would still be a win though, because unless someone actually uses the Flatpaks to verify PR's, are they _really_ necessary if it's just a game code PR? It shortens the PR feedback cycle (so can do more commits and still merge earlier) so then the slow master builds aren't much of an issue anymore.

**Comment by s09bQ5** [comment]
Is AppVeyor now fast enough?

**Comment by barbeque-squared** [comment]
Yeah this is fast enough. It was especially the flatpak build with wildly varying (but usually consistently longer than all the other jobs) build times.
