### ISSUE TITLE
Let's remove the cURL/OpenSSL/libidn DLLs

### ISSUE THREAD

**Issue by s09bQ5** [UltraStar-Deluxe/USDX#704]
We are shipping some very old DLLs for cURL and its dependencies libidn and OpenSSL. I think the idea was that a leaderboard plugin DLL could use these DLLs to access the server.

I believe it is not our responsibility to provide the dependencies for third-party plugins. I also doubt that someone maintaining a leaderboard plugin would still use dependencies that old. We are talking about DLLs for cURL 7.19.6 (August 2009) and OpenSSL 1.0.2l (May 2017). They must be riddled with security holes and they are not able to talk TLS 1.3. Current versions of cURL and OpenSSL are not API compatible. (And I wonder if a cURL that old was ever able to use OpenSSL 1.0.2 when @basisbit updated it in e36266df6fbd6ba5b4991c8e57e3cee66bec17d3)

Add to that the fact that very few users are using leaderboard plugins and that the DLLs amount to 2.3MB.

Do we know of any servers using leaderboard plugins?
Can we check if they depend on these DLLs?
If yes, can we ask them to provide the DLLs themselves?

**Comment by barbeque-squared** [comment]
I agree that these DLLs are not something USDX has to provide. USDX only provides some hooks for plugins to attach to, but whether a plugin wants to send scores by HTTP or SMS or pigeon shouldn't really be our concern. Though, when the installer is used (not the portable zip), there's also an `Update.exe`, maybe that depends on them? There's also (commented out I think) sections in the installer scripts about downloading stuff.

> Do we know of any servers using leaderboard plugins?
I'm only aware of two: [My Little Karaoke](https://www.mylittlekaraoke.com/) and [UltraStar ES](https://ultrastar-es.org/en/concursos/puntuaciones)

ES uses a completely different build (worldparty) so I would say that's not something we would need to worry about.

My Little Karaoke provides its own installer and/or separate leaderboard plugin. It shouldn't be too hard for them to also provide the DLLs they need in the future. I'll ask. And yeah IIRC they still use either plain HTTP or a really old TLS because of the oldness.

I'm not aware of any others.

**Comment by s09bQ5** [comment]
> Though, when the installer is used (not the portable zip), there's also an `Update.exe`, maybe that depends on them? There's also (commented out I think) sections in the installer scripts about downloading stuff.

Update.nsi uses the [Inetc](https://nsis.sourceforge.io/Inetc_plug-in) plugin to check the version of the latest release and then uses the [NSISdl](https://nsis.sourceforge.io/Builtin_NSISdl_plug-in) plugin to download the installer. None of them depend on our cURL or OpenSSL DLLs.

Btw., the version check in Update.nsi appears to broken currently as it relies on a branch "release" pointing to the tag of the latest release.

**Comment by barbeque-squared** [comment]
My Little Karaoke appears to (so far) be the only one.
