### ISSUE TITLE
How to use vocaluxe Neon theme skin with USDX

### ISSUE THREAD

**Issue by DerGitRob** [UltraStar-Deluxe/USDX#763]
There is a nice vocaluxe theme:
https://github.com/Vocaluxe/Vocaluxe/discussions/613

Is there a way to use that skin in Ultrastar Deluxe?

**Comment by barbeque-squared** [comment]
By copy-pasting: no

By manually creating the necessary .ini files that USDX understands: judging from the screenshots, you can probably do at least 95% of what that theme does (and then create bug reports for the things you _can't_ do or where USDX is refusing to adhere to the color or something).
It'll be a lot of manual work (most USDX themes are just reskins of the existing themes), but it's certainly not undoable if you have the free time.

I'm well aware that the USDX themes are... well, they're something. It's a ginormous .ini file with very few comments on what does what, though if you just add some random letters to the name between `[]` it will usually just not display that element anymore (or crash the game entirely, but the upcoming release should give less unhelpful output in Error.log).

That said, doing anything about the way themes work isn't really planned for anytime soon. I want to do something about it _at some point_ but that's only after I've gone through most of the internals, so that'll be some years away.
Maybe you can sponsor someone (not me) into making it if you want it short-term -- and if the license allows it, it could become part of USDX -- but I don't consider making custom themes a core USDX developer activity.
