### ISSUE TITLE
Video does not play

### ISSUE THREAD

**Issue by platinorum** [UltraStar-Deluxe/USDX#775]
### Actual behaviour

The video does not play.
Please see **Details** for more.

### Expected behaviour

Video plays normally

### Steps to reproduce

1. Add the mp4 file name to the song txt file.
2. Open USDX.
3. Note that the video does indeed not show.

### Details

If I add the mp4 filename in a separate line in the song txt file, it works as expected, here the order of the 2 lines does not matter. If I remove the other information in the `#VIDEO:` line (e.g. `v=`, `co=`, `bg=`), it also works as expected. The problem only occurs when the mp4 filename is included in the `#VIDEO:` line along with the other normal tags.
If I go to the song in USDX itself, then press `M` to open the menu, and then go to `Song` > `Edit`, the correct mp4 filename is displayed in the video field, so theoretically it should be recognized correctly.
At first I thought the problem might have to do with USDX not filtering the relevant information for the mp4 filename, but then I saw that it was recognized correctly in the editor.

- USDX version: v2023.9.0
- Operating System + version: Windows 10

**Comment by s09bQ5** [comment]
What are you trying to do? Please post an example.
Where did you read that other information can be added to the `#VIDEO` line?

**Comment by barbeque-squared** [comment]
> `v=`, `co=`, `bg=`

These look suspiciously much like tags from @bohning 's [USDB Syncer](https://github.com/bohning/usdb_syncer/wiki/Meta-Tags#format). That program more or less abuses the `#VIDEO` tag on USDB, but it can't really be helped because USDB doesn't allow custom tags (I hope that in the future it will be some more obvious tag like `#USDBSYNCER` or something)

What the USDX editor _shows_ should not be taken for granted. As long as you don't actually _change_ the value in the editor it will just use whatever is actually in the .txt file. But assuming you downloaded your txt from USDB directly, just replace the `#VIDEO:` line with `#VIDEO:myfile.mp4`.

I'm closing this for now because if you still have issues after this you really should post at least the txt lines that start with `#`, otherwise we cannot help you.

**Comment by s09bQ5** [comment]
We could try to strip these tags from the file name if the file can't be found with the tags attached. And the `co` and `bg` tags do contain information useful to USDX, so we might want to parse them.
