### ISSUE TITLE
How to Make 3-4 players sing their Own Unique parts on a Song/Duet or Truet or quartet?

### ISSUE THREAD

**Issue by jay54hunter** [UltraStar-Deluxe/USDX#776]
Each player sings Unique part
example
P1
: 0 10 20 First part of the song
-10
P2
:  11 10 20 Second Part
- 20
P3
: 0 10 20 third part of the song
-10
P4
:  11 10 20 fourth Part
- 20
P5
P1 and P2 sings Fifth part
P6
P3 and P4 sings
p7 All sings

or something even simplier.. like 3 players sing.

**Comment by barbeque-squared** [comment]
I'm going to link a few issues which _probably_ cover this request anyway and then close this because we have way too many requests that deal with this already. Please reopen it if the below tickets for some reason don't cover this specific usecase (but even if not, it's imo fairly pointless to think about until those other tickets are done).

#646 
#746 
https://github.com/UltraStar-Deluxe/format/issues/17

Regardless of how we do this it's going to require some rework on the USDX side of things (I'm not going to hack it in the way things were done in the past ~10 years) and it's all pointless if people are adamant about the _currently existing_ P3 behaviour.
