### ISSUE TITLE
Space not pausing the game

### ISSUE THREAD

**Issue by a3nima** [UltraStar-Deluxe/USDX#784]
### Actual behaviour

Pressing space does not pause the game.

### Expected behaviour
I was used to be able to pause with space. 

### Steps to reproduce

Play song press Space.

### Details

Provide some additional information:

- USDX version: v2023.12.0
- Operating System + version: Windows 10

**Comment by barbeque-squared** [comment]
this should already be fixed by #782, I just completely forgot people to test it. I know that one fixes at least the space pause problem, but I might have missed an input field somewhere because I never use certain modes.

it will probably get merged this month though and be released in 2024.1.0

**Comment by barbeque-squared** [comment]
In the meantime, you should still be able to pause/unpause with `P`. While the bug report isn't wrong, nor is my statement about the linked PR fixing it, I realized later that it would probably be useful to provide this short term workaround.

I've also added `P` as an alternative shortcut on the wiki page: https://github.com/UltraStar-Deluxe/USDX/wiki/Controls#shortcuts-for-sing-screen since it was missing there. I also checked the ingame help (only English) and it is already listed there.

**Comment by barbeque-squared** [comment]
fixed by #782 
there will be a 2024.1.0 release
