### ISSUE TITLE
medley mode has hardcoded "Easy" difficulty

### ISSUE THREAD

**Issue by barbeque-squared** [UltraStar-Deluxe/USDX#821]
Reported in Discord on Mar 17:

> Just a short report while singing: Difficulties medium & hard are not working in medley mode in usdx 2024.03 ... it just stays easy.

**Comment by DeinAlptraum** [comment]
The difficulty for medley mode is controlled by the global `Ini.Difficulty` setting, versus the per-player setting `Ini.PlayerLevel[<index>]`
In-game this setting can only be changed by starting party mode, which uses the same setting. There's also `UScreenLevel.pas` which allows changing this, but is itself apparently not accessible as far as I could tell.

Should this be changed for medley mode to use `Ini.PlayerLevel` instead of `Ini.Difficulty`?

**Comment by barbeque-squared** [comment]
> In-game this setting can only be changed by starting party mode

Can't say this surprises me. Party mode is a giant hack, to the point where I'd rather just delete it in its entirety.

> Should this be changed for medley mode

I would merge this!

**Comment by basisbit** [comment]
> Can't say this surprises me. Party mode is a giant hack, to the point where I'd rather just delete it in its entirety.

Not, party mode stays. Unfortunately many people use it. Please also don't break compatibility with the LUA plugins too much.
