### ISSUE TITLE
Install on linux container

### ISSUE THREAD

**Issue by madcar86** [UltraStar-Deluxe/USDX#825]
I am trying to install on a Linux LXC in Promox. I  am still very new to linux and I don't understand how to actually install the program. I have done a wget and git clone to get the repository on the LXC. But I don't know the next step to actually install. Any help would be appreciated.

**Comment by GrueneNeun** [comment]
Why? But I don't think it will work at all, because you don't have a GUI or a window manager in an lxc container.

**Comment by madcar86** [comment]
Maybe I dont understand how USDX works. I had assumed it was like other headless apps. That you use a web UI to connect to the stream to whatever you need to. Are there any videos that explain how to use it?

**Comment by barbeque-squared** [comment]
> I had assumed it was like other headless apps.

Which other apps/games would that be? I'm not aware of any karaoke apps that are really built like this, so I'm curious where this assumption is coming from.

If you want a container-like installation (ie not having to compile it yourself), you're probably better off looking here https://github.com/UltraStar-Deluxe/USDX?tab=readme-ov-file#2-installation and choosing either the appimage (look on the release page) or flathub.

I'm going to close this issue because running the _entire game_ through a browser like this ticket probably wants is not something that USDX is really suitable for. There's issues with latency and I also don't know how to use 6 microphones in a single browser tab.
