### ISSUE TITLE
Reenable sort menu in song selection

### ISSUE THREAD

**Issue by DeinAlptraum** [UltraStar-Deluxe/USDX#862]
### Actual behaviour

On the song selection screen, pressing M brings up the menu where the third point is "Sort". Selecting this gives an error that this is not available at the moment.

### Expected behaviour

This should open a menu allowing to change the sorting of the songs or something similar. Alternatively, the option should be removed from the menu if we deem it unnecesssary.

### Details

The actual call to the sort menu is currently commented out in the song, replaced with the aforementioned error message.
Adding this back in gives a mostly working menu: at the very least I was able to change the sorting from "Artist" to "Title" and that worked, though a few non-crash bugs seem to persist.

Here's what the menu looks like:
![Screenshot_20240710_105340](https://github.com/UltraStar-Deluxe/USDX/assets/51118500/13224320-16a8-400b-86a5-e14238666b2b)

**Comment by barbeque-squared** [comment]
* I've never used this feature (~7 years of USDX usage).
* I've never seen anyone else (intentionally) use this feature.
* I've removed the menu entry entirely in my local builds.
* I'm going to assume it's been "not available" since the beginning of the git history, but probably longer.
* You say there's "a few non-crash bugs" on Roulette, so it's probably worse on others.

I don't see any value in keeping any of this around, and we should not only remove it from the menu, but also go through the code and clean up whatever has to do with this.
(you'll probably end up with an empty row in the middle of the menu, because from messing around with my local build it's way too much effort to actually move menu items to different rows. stuff is hardcoded in so many places)
