### ISSUE TITLE
Easier difficulty switching [Enhancement]

### ISSUE THREAD

**Issue by eldan-dex** [UltraStar-Deluxe/USDX#91]
Having a hotkey or a songselection-menu option to change player difficulty, so that you wouldn't need to go back to the initial screen and change it there

**Comment by basisbit** [comment]
in options -> advanced there is the "After Song Select" setting. You can set that to "select players". Does that fulfill your requirement?

**Comment by basisbit** [comment]
also, in song selection window there is menu ->song -> change players.

**Comment by eldan-dex** [comment]
Yes, I wasn't aware of this. Thanks!

**Comment by RattleSN4K3** [comment]
A bit more on this, why this has been probably asked.

USDX should get rid of the so called difficulty (same as what the SingStar did). Instead it should go with a selectable reverse-handicap [sports]. The default level would be easy and a player can select in which reverse-handicap it would play (make it harder to score). The reason why reverse and starting at easy? This way both players are having the ability to score the highest points with the lowest effort, however the other player could easly demand (talkative) the opposite player to raise the level. If it would be a real-handicap or a selectable level in both directions, anyone will start at the easiest (likely).

An alternative way (requires 4 levels):
Instead of having easy as the default difficulty, it would be the next after it (let's call it _Medium_). The next difficulty could be _Hard_ with _Insane_ being the most difficulty one. The player could choose to go 1 down but 2 up.

This is another topic but I just wanted to mention to point of view about difficulty.
